### ISSUE TITLE
Cannot find module 'retry-axios' or its corresponding type declarations

### ISSUE THREAD

**Issue by markabrahams** [JustinBeckwith/retry-axios#224]
Hi

In retry-axios version 3.1.0, the ES-style import:
`
import * as rax from 'retry-axios';
`
fails to compile with Typescript compiler (v5.2.2) with default configuration with error:
`
main.ts:1:22 - error TS2307: Cannot find module 'retry-axios' or its corresponding type declarations.
`

retry-axios version 3.0.0 compiles fine with the same import.

A require is also fine with version 3.1.0:
`
const rax = require('retry-axios');
`

**Comment by steakyukke** [comment]
I think it is because `3.1.0` does not include `retry-axios/build/src/index.d.ts`.
